name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        POCKETBASE_TEST_ADMIN_EMAIL: ${{ secrets.POCKETBASE_TEST_ADMIN_EMAIL }}
        POCKETBASE_TEST_ADMIN_PASSWORD: ${{ secrets.POCKETBASE_TEST_ADMIN_PASSWORD }}
        POCKETBASE_TEST_USER_EMAIL: ${{ secrets.POCKETBASE_TEST_USER_EMAIL }}
        POCKETBASE_TEST_USER_PASSWORD: ${{ secrets.POCKETBASE_TEST_USER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test
